# Use postgres/example user/password credentials
version: '2'

services:

  db:
    image: postgres
    restart: always
    container_name: "waf-postgres"

    environment:
      POSTGRES_PASSWORD: secretpassword
    ports:
      - 5432:5432

  mongodb:
    image: mongo
    container_name: "waf-mongo"

    restart: always
    ports:
      - 27017:27017

  redisdb:
    image: redis
    container_name: "waf-redis"

    restart: always
    ports:
      - 6379:6379


  minio:
    image: minio/minio
    container_name: "waf-minio"
    command: server /data
    #volumes:
    #  - minio1-data:/export
    ports:
      - "9000:9000"

    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: SECRETSECRET

  woofapi:
    image: cryptodraco/sentinel-dev:v0.0.9
    container_name: "waf-api"
    hostname: woofapi
    restart: always
    #networks:
    #  local:
    #    aliases:
    #      - woofapi
    environment:
      - NUC=1 #environement de dev
      - NEED_HTTPS_FOR=wannanosuurus
      - INTERNAL_URL=http://woofapi:8080/ #doit mapper hostname + port externe + /
    depends_on:
      - minio
    links:
      - db
      - mongodb
      - redisdb
      - minio
    ports:
      - 8080:8080
