# Use postgres/example user/password credentials
version: '0.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword

  adminer:
    image: cryptodraco/sentinel-dev:v0.0.5
    restart: always
    environment:
      - NUC=1 #environement de dev
    links:
      - db
    ports:
      - 5000:8080
