# Use postgres/example user/password credentials
version: '2'

services:

  db:
    image: postgres
    restart: always
    container_name: "waf-postgres"

    environment:
      POSTGRES_PASSWORD: secretpassword

  mongodb:
    image: mongo
    container_name: "waf-mongo"

    restart: always
    ports:
      - 27017:27017

  redisdb:
    image: redis
    container_name: "waf-redis"

    restart: always
    ports:
      - 6379:6379


  woofapi:
    image: cryptodraco/sentinel-dev:v0.0.7
    container_name: "waf-api"
    hostname: woofapi
    restart: always
    #networks:
    #  local:
    #    aliases:
    #      - woofapi
    environment:
      - NUC=1 #environement de dev
      - INTERNAL_URL=http://woofapi:8080 #doit mapper hostname + port externe
    links:
      - db
      - mongodb
      - redisdb
    ports:
      - 5002:8080
