"""empty message

Revision ID: 05c724bdb52e
Revises: 1c78e8a0e137
Create Date: 2018-04-08 15:15:32.912675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c724bdb52e'
down_revision = '1c78e8a0e137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('_petowner_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'pet_petowner_id_fkey', 'pet', type_='foreignkey')
    op.create_foreign_key(None, 'pet', 'petsowner', ['_petowner_id'], ['id'])
    op.drop_column('pet', 'petowner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('petowner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.create_foreign_key(u'pet_petowner_id_fkey', 'pet', 'petsowner', ['petowner_id'], ['id'])
    op.drop_column('pet', '_petowner_id')
    # ### end Alembic commands ###
