"""empty message

Revision ID: 0a8300dd2480
Revises: a95252bdce7d
Create Date: 2018-04-18 18:10:00.027926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a8300dd2480'
down_revision = 'a95252bdce7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('cre_date', sa.DateTime(), nullable=True))
    op.drop_column('feed', 'pub_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('pub_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('feed', 'cre_date')
    # ### end Alembic commands ###
