"""empty message

Revision ID: 1c78e8a0e137
Revises: 57caf6ab7bc9
Create Date: 2018-04-08 12:58:58.622323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c78e8a0e137'
down_revision = '57caf6ab7bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petsowner', sa.Column('_provider_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petsowner', '_provider_id')
    # ### end Alembic commands ###
