"""empty message

Revision ID: 29ec3eb17d77
Revises: 88811bc8431a
Create Date: 2018-04-17 09:59:01.020240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ec3eb17d77'
down_revision = '88811bc8431a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('test', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'test')
    # ### end Alembic commands ###
