"""empty message

Revision ID: 41b7ba29d568
Revises: 1ad9f4d1fc22
Create Date: 2018-04-06 15:39:30.185030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41b7ba29d568'
down_revision = '1ad9f4d1fc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petsowner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentinel_id', sa.Integer(), nullable=True),
    sa.Column('mail', sa.String(length=50), nullable=True),
    sa.Column('seed', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('woof_name', sa.String(length=41), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['petsowner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'stations_pkey')
    )
    op.drop_table('pet')
    op.drop_table('petsowner')
    # ### end Alembic commands ###
