"""empty message

Revision ID: 45c4e3c28a20
Revises: 0a8300dd2480
Create Date: 2018-04-18 18:27:50.105582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c4e3c28a20'
down_revision = '0a8300dd2480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('myfriend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['myfriend_id'], ['petsowner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
