"""empty message

Revision ID: 57caf6ab7bc9
Revises: d83711187f15
Create Date: 2018-04-07 15:11:19.839335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57caf6ab7bc9'
down_revision = 'd83711187f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petsowner', sa.Column('_sentinel_id', sa.String(length=40), nullable=True))
    op.drop_column('petsowner', 'sentinel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petsowner', sa.Column('sentinel_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('petsowner', '_sentinel_id')
    # ### end Alembic commands ###
