"""empty message

Revision ID: 6366113345f8
Revises: 29ec3eb17d77
Create Date: 2018-04-17 10:03:29.298451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6366113345f8'
down_revision = '29ec3eb17d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'comment',
               existing_type=sa.VARCHAR(length=41),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.drop_column('feed', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('test', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.alter_column('feed', 'comment',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=41),
               existing_nullable=True)
    # ### end Alembic commands ###
