"""empty message

Revision ID: 88811bc8431a
Revises: d754a0a6c49a
Create Date: 2018-04-16 16:57:18.556302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88811bc8431a'
down_revision = 'd754a0a6c49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_feed', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.String(length=41), nullable=True),
    sa.Column('_pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    # ### end Alembic commands ###
