"""empty message

Revision ID: 8a45e5f642bf
Revises: fa74423e7a69
Create Date: 2018-04-19 21:35:44.881539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a45e5f642bf'
down_revision = 'fa74423e7a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'uuid',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=124),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'uuid',
               existing_type=sa.String(length=124),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
