"""empty message

Revision ID: 8bb6e0536358
Revises: 625c49efaa60
Create Date: 2018-04-18 14:08:43.176208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb6e0536358'
down_revision = '625c49efaa60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('uuid', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'uuid')
    # ### end Alembic commands ###
