"""empty message

Revision ID: 98ab210b67a1
Revises: e06afa4ef752
Create Date: 2018-04-19 11:12:26.479394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ab210b67a1'
down_revision = 'e06afa4ef752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('extra_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'extra_field')
    # ### end Alembic commands ###
