"""empty message

Revision ID: a95252bdce7d
Revises: 9ede84af38e4
Create Date: 2018-04-18 18:01:05.132782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95252bdce7d'
down_revision = '9ede84af38e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('mod_date', sa.DateTime(), nullable=True))
    op.add_column('pet', sa.Column('cre_date', sa.DateTime(), nullable=True))
    op.add_column('petsowner', sa.Column('cre_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petsowner', 'cre_date')
    op.drop_column('pet', 'cre_date')
    op.drop_column('feed', 'mod_date')
    # ### end Alembic commands ###
