"""empty message

Revision ID: d24a4ba36138
Revises: 
Create Date: 2018-04-06 21:16:06.424516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24a4ba36138'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petsowner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentinel_id', sa.String(length=40), nullable=True),
    sa.Column('mail', sa.String(length=50), nullable=True),
    sa.Column('seed', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('woof_name', sa.String(length=41), nullable=True),
    sa.Column('petowner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petowner_id'], ['petsowner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('petsowner')
    # ### end Alembic commands ###
