"""empty message

Revision ID: d754a0a6c49a
Revises: 05c724bdb52e
Create Date: 2018-04-16 14:37:05.983921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd754a0a6c49a'
down_revision = '05c724bdb52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('url_badge', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'url_badge')
    # ### end Alembic commands ###
