"""empty message

Revision ID: d83711187f15
Revises: d24a4ba36138
Create Date: 2018-04-07 10:40:41.993275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83711187f15'
down_revision = 'd24a4ba36138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petsowner', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petsowner', 'name')
    # ### end Alembic commands ###
