"""empty message

Revision ID: e06afa4ef752
Revises: 
Create Date: 2018-04-18 20:05:58.566770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06afa4ef752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petsowner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_sentinel_id', sa.String(length=40), nullable=True),
    sa.Column('_provider_id', sa.String(length=100), nullable=True),
    sa.Column('mail', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('seed', sa.String(length=20), nullable=True),
    sa.Column('cre_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('myfriend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['petsowner.id'], ),
    sa.ForeignKeyConstraint(['myfriend_id'], ['petsowner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('url_badge', sa.String(length=150), nullable=True),
    sa.Column('woof_name', sa.String(length=41), nullable=True),
    sa.Column('_petowner_id', sa.Integer(), nullable=True),
    sa.Column('cre_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['_petowner_id'], ['petsowner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_feed', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.Column('cre_date', sa.DateTime(), nullable=True),
    sa.Column('mod_date', sa.DateTime(), nullable=True),
    sa.Column('_pet_id', sa.Integer(), nullable=True),
    sa.Column('_petowner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    op.drop_table('pet')
    op.drop_table('friends')
    op.drop_table('petsowner')
    # ### end Alembic commands ###
